/**
 * Demo Mode Data
 *
 * When the app is running on GitHub Pages (no backend), all API calls
 * resolve against this hardcoded data so judges can explore the full UX.
 */

import { Scholarship } from "@/components/discover/SwipeCard";

// ─── Demo User ───────────────────────────────────────────────
export const DEMO_USER = {
  id: 1,
  email: "demo@echelon.ai",
  full_name: "Sarah Chen",
  onboarding_complete: true,
  major: "Computer Science",
  gpa: "3.8",
  education_level: "Undergraduate",
  institution: "University of Toronto",
  grad_year: "2027",
  gender: "Female",
  ethnicity: "Asian",
  dob: "2004-06-15",
  extracurriculars: "Hackathon Club President, AI Research Lab",
  awards: "Dean's List, National Science Fair Winner",
  volunteer_work: "Code Mentor at Girls Who Code",
};

// ─── Profile Stats ───────────────────────────────────────────
export const DEMO_STATS = {
  total_won: 0,
  total_potential_value: 293000,
  applied_count: 3,
  saved_count: 4,
  won_count: 0,
  lost_count: 0,
  win_rate: 0,
  profile_completeness: 75,
  missing_fields: ["volunteer_work", "awards", "dob"],
};

// ─── Swipe Feed ──────────────────────────────────────────────
export const DEMO_SCHOLARSHIPS: Scholarship[] = [
  {
    id: "1",
    provider_name: "Google",
    title: "Women Techmakers Scholarship",
    amount: 10000,
    deadline_days: 3,
    win_probability: 87,
    effort_hours: 2,
    tags: ["STEM", "Women", "Undergrad"],
    description:
      "For women studying computer science or a related field. Essay required about your impact on the community.",
    color_start: "from-blue-600",
    color_end: "to-cyan-500",
  },
  {
    id: "2",
    provider_name: "Microsoft",
    title: "Microsoft SWE Scholarship",
    amount: 20000,
    deadline_days: 12,
    win_probability: 80,
    effort_hours: 4,
    tags: ["Tech", "Diversity", "CS Major"],
    description:
      "Supporting underrepresented students in computer science. Strong academics and leadership required.",
    color_start: "from-indigo-600",
    color_end: "to-violet-500",
  },
  {
    id: "3",
    provider_name: "Taco Bell",
    title: "Live Más Scholarship",
    amount: 25000,
    deadline_days: 5,
    win_probability: 62,
    effort_hours: 1,
    tags: ["Video", "Creative", "No-Essay"],
    description:
      "Create a 2-minute video about your passion. No grades or essays required.",
    color_start: "from-purple-600",
    color_end: "to-fuchsia-500",
  },
  {
    id: "4",
    provider_name: "Gates Foundation",
    title: "The Gates Scholarship",
    amount: 50000,
    deadline_days: 45,
    win_probability: 15,
    effort_hours: 12,
    tags: ["Leadership", "Low-Income", "Minority"],
    description:
      "A highly selective, last-dollar scholarship for outstanding minority students with strong leadership.",
    color_start: "from-slate-800",
    color_end: "to-slate-600",
  },
  {
    id: "5",
    provider_name: "Amazon",
    title: "Amazon Future Engineer Scholarship",
    amount: 40000,
    deadline_days: 21,
    win_probability: 45,
    effort_hours: 5,
    tags: ["Engineering", "CS", "Internship"],
    description:
      "Includes $40,000 scholarship plus a guaranteed internship at Amazon for CS students.",
    color_start: "from-amber-500",
    color_end: "to-orange-600",
  },
  {
    id: "6",
    provider_name: "Shopify",
    title: "Shopify Dev Degree Scholarship",
    amount: 15000,
    deadline_days: 30,
    win_probability: 55,
    effort_hours: 3,
    tags: ["Canadian", "Dev", "Co-op"],
    description:
      "For Canadian students combining a CS degree with hands-on development experience at Shopify.",
    color_start: "from-emerald-600",
    color_end: "to-teal-500",
  },
  {
    id: "7",
    provider_name: "CIBC",
    title: "CIBC Achievement Scholarship",
    amount: 8000,
    deadline_days: 14,
    win_probability: 70,
    effort_hours: 2,
    tags: ["Canadian", "GPA 3.5+", "Finance"],
    description:
      "Rewarding Canadian undergraduate students who demonstrate academic excellence and community involvement.",
    color_start: "from-red-600",
    color_end: "to-red-400",
  },
  {
    id: "8",
    provider_name: "Thiel Foundation",
    title: "Thiel Fellowship",
    amount: 100000,
    deadline_days: 90,
    win_probability: 3,
    effort_hours: 20,
    tags: ["Entrepreneurship", "Under 22", "Startup"],
    description:
      "For young people who want to build new things instead of sitting in a classroom. $100K over 2 years.",
    color_start: "from-orange-500",
    color_end: "to-red-600",
  },
];

// ─── Tracker Applications ────────────────────────────────────
export const DEMO_APPLICATIONS = [
  {
    id: "app-1",
    scholarship_id: "101",
    status: "Saved",
    provider_name: "RBC",
    title: "RBC Capital Markets Scholarship",
    amount: 10000,
    deadline_days: 18,
    win_probability: 72,
    color_start: "from-blue-700",
    color_end: "to-blue-500",
  },
  {
    id: "app-2",
    scholarship_id: "102",
    status: "Saved",
    provider_name: "TD Bank",
    title: "TD Scholarship for Community Leadership",
    amount: 70000,
    deadline_days: 25,
    win_probability: 30,
    color_start: "from-emerald-700",
    color_end: "to-green-600",
  },
  {
    id: "app-3",
    scholarship_id: "103",
    status: "Saved",
    provider_name: "Loran",
    title: "Loran Scholars Foundation Award",
    amount: 100000,
    deadline_days: 40,
    win_probability: 12,
    color_start: "from-slate-700",
    color_end: "to-zinc-600",
  },
  {
    id: "app-4",
    scholarship_id: "104",
    status: "Saved",
    provider_name: "Schulich",
    title: "Schulich Leader Scholarships",
    amount: 120000,
    deadline_days: 60,
    win_probability: 8,
    color_start: "from-amber-500",
    color_end: "to-orange-500",
  },
  {
    id: "app-5",
    scholarship_id: "105",
    status: "Applied",
    provider_name: "Google",
    title: "Women Techmakers Scholarship",
    amount: 10000,
    deadline_days: 3,
    win_probability: 87,
    color_start: "from-blue-600",
    color_end: "to-cyan-500",
  },
  {
    id: "app-6",
    scholarship_id: "106",
    status: "Applied",
    provider_name: "Amazon",
    title: "Amazon Future Engineer",
    amount: 40000,
    deadline_days: 21,
    win_probability: 45,
    color_start: "from-amber-500",
    color_end: "to-orange-600",
  },
  {
    id: "app-7",
    scholarship_id: "107",
    status: "Applied",
    provider_name: "Shopify",
    title: "Shopify Dev Degree Scholarship",
    amount: 15000,
    deadline_days: 30,
    win_probability: 55,
    color_start: "from-emerald-600",
    color_end: "to-teal-500",
  },
  {
    id: "app-8",
    scholarship_id: "108",
    status: "In Review",
    provider_name: "Taco Bell",
    title: "Live Más Scholarship",
    amount: 25000,
    deadline_days: 5,
    win_probability: 62,
    color_start: "from-purple-600",
    color_end: "to-fuchsia-500",
  },
  {
    id: "app-9",
    scholarship_id: "109",
    status: "In Review",
    provider_name: "Microsoft",
    title: "Microsoft SWE Scholarship",
    amount: 20000,
    deadline_days: 12,
    win_probability: 80,
    color_start: "from-indigo-600",
    color_end: "to-violet-500",
  },
  {
    id: "app-10",
    scholarship_id: "110",
    status: "In Review",
    provider_name: "CIBC",
    title: "CIBC Achievement Scholarship",
    amount: 8000,
    deadline_days: 14,
    win_probability: 70,
    color_start: "from-red-600",
    color_end: "to-red-400",
  },
];
