/**
 * Demo Mode Data
 *
 * When the app is running on GitHub Pages (no backend), all API calls
 * resolve against this hardcoded data so judges can explore the full UX.
 */

import { Scholarship } from "@/components/discover/SwipeCard";

// ─── Demo User ───────────────────────────────────────────────
export const DEMO_USER = {
  id: 1,
  email: "demo@echelon.ai",
  full_name: "Amara Okafor",
  onboarding_complete: true,
  major: "Computer Science",
  gpa: "3.8",
  education_level: "Undergraduate",
  institution: "University of Toronto",
  grad_year: "2027",
  gender: "Female",
  ethnicity: "Black / African",
  dob: "2004-09-22",
  extracurriculars: "NSBE Chapter President, AI Research Lab, Hackathon Club",
  awards: "Dean's List, Google Code Jam Finalist, UofT Equity Scholarship",
  volunteer_work: "Mentor at Black Boys Code, Math Tutor at Jane-Finch Community Centre",
};

// ─── Profile Stats ───────────────────────────────────────────
export const DEMO_STATS = {
  total_won: 0,
  total_potential_value: 347000,
  applied_count: 5,
  saved_count: 6,
  won_count: 0,
  lost_count: 0,
  win_rate: 0,
  profile_completeness: 82,
  missing_fields: ["resume", "reference_letter"],
};

// ─── Swipe Feed ──────────────────────────────────────────────
export const DEMO_SCHOLARSHIPS: Scholarship[] = [
  {
    id: "1",
    provider_name: "UNCF",
    title: "UNCF Scholarships",
    amount: 25000,
    deadline_days: 7,
    win_probability: 82,
    effort_hours: 3,
    tags: ["Black Students", "GPA 3.5+", "Undergrad"],
    description:
      "United Negro College Fund scholarship for Black undergraduates demonstrating academic excellence and leadership potential.",
    color_start: "from-amber-600",
    color_end: "to-yellow-500",
  },
  {
    id: "2",
    provider_name: "Ron Brown",
    title: "Ron Brown Scholar Program",
    amount: 40000,
    deadline_days: 14,
    win_probability: 25,
    effort_hours: 8,
    tags: ["Black Students", "Leadership", "Community"],
    description:
      "For academically talented and highly motivated Black students who demonstrate community service and leadership.",
    color_start: "from-slate-800",
    color_end: "to-slate-600",
  },
  {
    id: "3",
    provider_name: "Google",
    title: "Google Generation Scholarship",
    amount: 10000,
    deadline_days: 5,
    win_probability: 78,
    effort_hours: 2,
    tags: ["STEM", "Underrepresented", "CS Major"],
    description:
      "For underrepresented students in tech. Includes mentorship and networking events at Google campus.",
    color_start: "from-blue-600",
    color_end: "to-cyan-500",
  },
  {
    id: "4",
    provider_name: "Jackie Robinson",
    title: "Jackie Robinson Foundation Scholarship",
    amount: 30000,
    deadline_days: 21,
    win_probability: 20,
    effort_hours: 10,
    tags: ["Black Students", "Leadership", "Mentorship"],
    description:
      "A 4-year scholarship for minority students showing leadership, academic achievement, and financial need. Includes mentoring.",
    color_start: "from-indigo-700",
    color_end: "to-blue-500",
  },
  {
    id: "5",
    provider_name: "Microsoft",
    title: "Microsoft Blacks at Microsoft Scholarship",
    amount: 20000,
    deadline_days: 18,
    win_probability: 72,
    effort_hours: 4,
    tags: ["Tech", "Black Students", "CS Major"],
    description:
      "Supporting Black and African American students pursuing degrees in computer science, engineering, or related STEM fields.",
    color_start: "from-indigo-600",
    color_end: "to-violet-500",
  },
  {
    id: "6",
    provider_name: "Amazon",
    title: "Amazon Future Engineer Scholarship",
    amount: 40000,
    deadline_days: 25,
    win_probability: 45,
    effort_hours: 5,
    tags: ["Engineering", "CS", "Internship"],
    description:
      "Includes $40,000 scholarship plus a guaranteed internship at Amazon for CS students from underrepresented backgrounds.",
    color_start: "from-amber-500",
    color_end: "to-orange-600",
  },
  {
    id: "7",
    provider_name: "TMCF",
    title: "Thurgood Marshall College Fund",
    amount: 15000,
    deadline_days: 10,
    win_probability: 65,
    effort_hours: 3,
    tags: ["Black Students", "HBCU", "Academic"],
    description:
      "Supporting students at HBCUs and predominantly Black institutions with scholarships, career prep, and internships.",
    color_start: "from-emerald-700",
    color_end: "to-teal-500",
  },
  {
    id: "8",
    provider_name: "Shopify",
    title: "Shopify Dev Degree Scholarship",
    amount: 15000,
    deadline_days: 30,
    win_probability: 55,
    effort_hours: 3,
    tags: ["Canadian", "Dev", "Co-op"],
    description:
      "For Canadian students combining a CS degree with hands-on development experience at Shopify.",
    color_start: "from-emerald-600",
    color_end: "to-teal-500",
  },
  {
    id: "9",
    provider_name: "Gates Foundation",
    title: "The Gates Scholarship",
    amount: 50000,
    deadline_days: 45,
    win_probability: 15,
    effort_hours: 12,
    tags: ["Leadership", "Low-Income", "Minority"],
    description:
      "A highly selective, last-dollar scholarship for outstanding minority students with strong leadership.",
    color_start: "from-slate-800",
    color_end: "to-zinc-500",
  },
  {
    id: "10",
    provider_name: "NACME",
    title: "NACME Engineering Scholarship",
    amount: 12000,
    deadline_days: 8,
    win_probability: 68,
    effort_hours: 2,
    tags: ["Engineering", "Minority", "STEM"],
    description:
      "National Action Council for Minorities in Engineering award for underrepresented students in engineering and CS.",
    color_start: "from-sky-600",
    color_end: "to-blue-500",
  },
  {
    id: "11",
    provider_name: "Taco Bell",
    title: "Live Más Scholarship",
    amount: 25000,
    deadline_days: 5,
    win_probability: 62,
    effort_hours: 1,
    tags: ["Video", "Creative", "No-Essay"],
    description:
      "Create a 2-minute video about your passion. No grades or essays required.",
    color_start: "from-purple-600",
    color_end: "to-fuchsia-500",
  },
  {
    id: "12",
    provider_name: "CIBC",
    title: "CIBC Achievement Scholarship",
    amount: 8000,
    deadline_days: 14,
    win_probability: 70,
    effort_hours: 2,
    tags: ["Canadian", "GPA 3.5+", "Finance"],
    description:
      "Rewarding Canadian undergraduate students who demonstrate academic excellence and community involvement.",
    color_start: "from-red-600",
    color_end: "to-red-400",
  },
  {
    id: "13",
    provider_name: "BHM",
    title: "Black History Month Scholarship",
    amount: 10000,
    deadline_days: 3,
    win_probability: 74,
    effort_hours: 2,
    tags: ["Black Students", "Essay", "Heritage"],
    description:
      "Annual scholarship celebrating Black excellence. Submit a 500-word essay on how your heritage shapes your ambitions.",
    color_start: "from-rose-600",
    color_end: "to-pink-500",
  },
  {
    id: "14",
    provider_name: "Thiel Foundation",
    title: "Thiel Fellowship",
    amount: 100000,
    deadline_days: 90,
    win_probability: 3,
    effort_hours: 20,
    tags: ["Entrepreneurship", "Under 22", "Startup"],
    description:
      "For young people who want to build new things instead of sitting in a classroom. $100K over 2 years.",
    color_start: "from-orange-500",
    color_end: "to-red-600",
  },
  {
    id: "15",
    provider_name: "NSBE",
    title: "NSBE Scholarship",
    amount: 7500,
    deadline_days: 12,
    win_probability: 80,
    effort_hours: 2,
    tags: ["Black Engineers", "STEM", "Undergrad"],
    description:
      "National Society of Black Engineers scholarship for members pursuing STEM degrees with strong academics.",
    color_start: "from-yellow-600",
    color_end: "to-amber-500",
  },
];

// ─── Tracker Applications ────────────────────────────────────
export const DEMO_APPLICATIONS = [
  // ── Saved (6) ──
  {
    id: "app-1",
    scholarship_id: "201",
    status: "Saved",
    provider_name: "UNCF",
    title: "UNCF Scholarships",
    amount: 25000,
    deadline_days: 7,
    win_probability: 82,
    color_start: "from-amber-600",
    color_end: "to-yellow-500",
  },
  {
    id: "app-2",
    scholarship_id: "202",
    status: "Saved",
    provider_name: "Ron Brown",
    title: "Ron Brown Scholar Program",
    amount: 40000,
    deadline_days: 14,
    win_probability: 25,
    color_start: "from-slate-800",
    color_end: "to-slate-600",
  },
  {
    id: "app-3",
    scholarship_id: "203",
    status: "Saved",
    provider_name: "Jackie Robinson",
    title: "Jackie Robinson Foundation",
    amount: 30000,
    deadline_days: 21,
    win_probability: 20,
    color_start: "from-indigo-700",
    color_end: "to-blue-500",
  },
  {
    id: "app-4",
    scholarship_id: "204",
    status: "Saved",
    provider_name: "TD Bank",
    title: "TD Scholarship for Community Leadership",
    amount: 70000,
    deadline_days: 25,
    win_probability: 30,
    color_start: "from-emerald-700",
    color_end: "to-green-600",
  },
  {
    id: "app-5",
    scholarship_id: "205",
    status: "Saved",
    provider_name: "Loran",
    title: "Loran Scholars Foundation Award",
    amount: 100000,
    deadline_days: 40,
    win_probability: 12,
    color_start: "from-slate-700",
    color_end: "to-zinc-600",
  },
  {
    id: "app-6",
    scholarship_id: "206",
    status: "Saved",
    provider_name: "Schulich",
    title: "Schulich Leader Scholarships",
    amount: 120000,
    deadline_days: 60,
    win_probability: 8,
    color_start: "from-amber-500",
    color_end: "to-orange-500",
  },
  // ── Applied (5) ──
  {
    id: "app-7",
    scholarship_id: "207",
    status: "Applied",
    provider_name: "Google",
    title: "Google Generation Scholarship",
    amount: 10000,
    deadline_days: 5,
    win_probability: 78,
    color_start: "from-blue-600",
    color_end: "to-cyan-500",
  },
  {
    id: "app-8",
    scholarship_id: "208",
    status: "Applied",
    provider_name: "Amazon",
    title: "Amazon Future Engineer",
    amount: 40000,
    deadline_days: 25,
    win_probability: 45,
    color_start: "from-amber-500",
    color_end: "to-orange-600",
  },
  {
    id: "app-9",
    scholarship_id: "209",
    status: "Applied",
    provider_name: "Shopify",
    title: "Shopify Dev Degree Scholarship",
    amount: 15000,
    deadline_days: 30,
    win_probability: 55,
    color_start: "from-emerald-600",
    color_end: "to-teal-500",
  },
  {
    id: "app-10",
    scholarship_id: "210",
    status: "Applied",
    provider_name: "NSBE",
    title: "NSBE Scholarship",
    amount: 7500,
    deadline_days: 12,
    win_probability: 80,
    color_start: "from-yellow-600",
    color_end: "to-amber-500",
  },
  {
    id: "app-11",
    scholarship_id: "211",
    status: "Applied",
    provider_name: "NACME",
    title: "NACME Engineering Scholarship",
    amount: 12000,
    deadline_days: 8,
    win_probability: 68,
    color_start: "from-sky-600",
    color_end: "to-blue-500",
  },
  // ── In Review (4) ──
  {
    id: "app-12",
    scholarship_id: "212",
    status: "In Review",
    provider_name: "Microsoft",
    title: "Blacks at Microsoft Scholarship",
    amount: 20000,
    deadline_days: 18,
    win_probability: 72,
    color_start: "from-indigo-600",
    color_end: "to-violet-500",
  },
  {
    id: "app-13",
    scholarship_id: "213",
    status: "In Review",
    provider_name: "TMCF",
    title: "Thurgood Marshall College Fund",
    amount: 15000,
    deadline_days: 10,
    win_probability: 65,
    color_start: "from-emerald-700",
    color_end: "to-teal-500",
  },
  {
    id: "app-14",
    scholarship_id: "214",
    status: "In Review",
    provider_name: "Taco Bell",
    title: "Live Más Scholarship",
    amount: 25000,
    deadline_days: 5,
    win_probability: 62,
    color_start: "from-purple-600",
    color_end: "to-fuchsia-500",
  },
  {
    id: "app-15",
    scholarship_id: "215",
    status: "In Review",
    provider_name: "CIBC",
    title: "CIBC Achievement Scholarship",
    amount: 8000,
    deadline_days: 14,
    win_probability: 70,
    color_start: "from-red-600",
    color_end: "to-red-400",
  },
];
